public with sharing class Constants {
    public static final Integer MAX_PRESETS = 3;
    public static final String ARMOR_OBJECT_LABEL = System.Label.Armor_Object_Label;
    public static final String WEAPON_OBJECT_LABEL = System.Label.Weapon_Object_Label;
    public static final String JEWELLERY_OBJECT_LABEL = System.Label.Jewellery_Object_Label;
    public static final String CONSUMABLE_OBJECT_LABEL = System.Label.Consumable_Object_Label;
    public static final String OTHER_OBJECT_LABEL = System.Label.Other_Item_Object_Label;
    
    public static final String WEAPON_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/weapon';
    public static final String ARMOR_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/armor';
    public static final String JEWELLERY_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/jewellery';
    public static final String CONSUMABLE_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/consumable';
    public static final String OTHER_ITEMS_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/other';

    public static final String WEAPON_UNLOAD_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/unloadweapons';
    public static final String ARMOR_UNLOAD_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/unloadarmor';
    public static final String JEWELLERY_UNLOAD_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/unloadjewellery';
    public static final String CONSUMABLE_UNLOAD_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/unloadconsumables';
    public static final String OTHER_ITEMS_UNLOAD_ENDPOINT = 'https://abracadabrant-mandarine-50120.herokuapp.com/items/unloadother';
}